import type { ResumeTemplate } from "./types";

export const templates: ResumeTemplate[] = [
  {
    id: "ats-classic",
    name: "ATS Classic",
    bestFor: "Conservative applications, online portals, and recruiter parsing.",
    atsRisk: "low",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: 10.6,
    lineHeight: 1.34,
    margin: 0.55,
    accentColor: "#0f766e",
    headingStyle: "rule",
    bulletSpacing: "compact",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "technical",
    name: "Technical Resume",
    bestFor: "Engineering, data, platform, and security roles.",
    atsRisk: "low",
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: 10.4,
    lineHeight: 1.36,
    margin: 0.55,
    accentColor: "#2563eb",
    headingStyle: "accent",
    bulletSpacing: "compact",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "executive",
    name: "Executive",
    bestFor: "General management, strategy, P&L, and board-facing profiles.",
    atsRisk: "medium",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: 10.8,
    lineHeight: 1.4,
    margin: 0.62,
    accentColor: "#7c2d12",
    headingStyle: "caps",
    bulletSpacing: "normal",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "operations",
    name: "Operations Leader",
    bestFor: "Logistics, supply chain, field operations, and process leadership.",
    atsRisk: "low",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: 10.5,
    lineHeight: 1.36,
    margin: 0.56,
    accentColor: "#166534",
    headingStyle: "rule",
    bulletSpacing: "compact",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "product",
    name: "Product Leader",
    bestFor: "PM, product strategy, growth, and platform leadership.",
    atsRisk: "medium",
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: 10.6,
    lineHeight: 1.38,
    margin: 0.58,
    accentColor: "#9333ea",
    headingStyle: "accent",
    bulletSpacing: "normal",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    bestFor: "Security engineering, GRC, incident response, and SOC roles.",
    atsRisk: "low",
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: 10.35,
    lineHeight: 1.33,
    margin: 0.52,
    accentColor: "#be123c",
    headingStyle: "boxed",
    bulletSpacing: "compact",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "sales-bd",
    name: "Sales/BD",
    bestFor: "Revenue, partnerships, business development, and account leadership.",
    atsRisk: "medium",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: 10.6,
    lineHeight: 1.38,
    margin: 0.58,
    accentColor: "#b45309",
    headingStyle: "accent",
    bulletSpacing: "normal",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "academic",
    name: "Academic CV",
    bestFor: "Academic, research, publications, talks, and grants.",
    atsRisk: "low",
    fontFamily: "Georgia, 'Times New Roman', serif",
    fontSize: 10.7,
    lineHeight: 1.42,
    margin: 0.65,
    accentColor: "#334155",
    headingStyle: "rule",
    bulletSpacing: "airy",
    layout: "single",
    pageSize: "a4",
  },
  {
    id: "minimal-one-page",
    name: "Minimal One Page",
    bestFor: "Early career, concise senior profiles, and networking handoffs.",
    atsRisk: "low",
    fontFamily: "Arial, Helvetica, sans-serif",
    fontSize: 10.15,
    lineHeight: 1.26,
    margin: 0.45,
    accentColor: "#0f172a",
    headingStyle: "caps",
    bulletSpacing: "compact",
    layout: "single",
    pageSize: "letter",
  },
  {
    id: "modern-two-column",
    name: "Modern Two Column",
    bestFor: "Human-readable portfolios and referrals where visual hierarchy helps.",
    atsRisk: "high",
    fontFamily: "Inter, Arial, sans-serif",
    fontSize: 10.2,
    lineHeight: 1.35,
    margin: 0.52,
    accentColor: "#0f766e",
    headingStyle: "accent",
    bulletSpacing: "normal",
    layout: "two-column",
    pageSize: "letter",
  },
];

export const getTemplate = (id?: string) =>
  templates.find((template) => template.id === id) ?? templates[0];
